### PR TITLE
Fix bug Mission terminated after first mission

### PR DESCRIPTION
**Pull request by bozoweed**

### CODE REVIEW

**Comment by dkdknight** [comment]
thank you for fix i try it now

**Comment by dkdknight** [comment]
That work thank you for fix

**Comment by propstg** [comment]
Thanks for the PR, @bozoweed. 

I haven't had a chance to test this, but I'm curious... Does this allow killing the patients?

I could be wrong, but it seems that if this line was the issue, `IsPedDeadOrDying` must have always returned true. The only way I think this would fix the issue is if `DoesEntityExist` always returns false, which would then skip the dead/dying check. (Unless calling `DoesEntityExist` does something spooky behind the scenes to make `IsPedDeadOrDying` return the correct result.)

**Comment by bozoweed** [comment]
hi @propstg , the entiyDoesExist is for check if entity of patient exist , because if not exist IsPedDeadOrDying return true because entity seem not finish spawn and so it's can't be alive , i can ask for try about kill npc to my friend , i get fix it for him

**Comment by MolenBeekRP** [comment]
Works but now NO peds (npc) are visible annymore... Howto fix that so there are standing peds (npcs) again

**Comment by propstg** [comment]
Thanks for providing a temporary workaround, @bozoweed. I've merged a change to fix the underlying issue, so I'm going to close this.

**Pull request closed without merging**
